# Generated by Django 5.0 on 2023-12-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Input name author', max_length=100, verbose_name='First name author')),
                ('last_name', models.CharField(help_text='Input last author', max_length=100, verbose_name='Last name author')),
                ('date_of_birth', models.DateField(blank=True, help_text='Input birthday', null=True, verbose_name='Birthday author')),
                ('about', models.TextField(help_text='Input about author', verbose_name='About author')),
                ('photo', models.ImageField(upload_to='author/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input genre', max_length=200, verbose_name='Genre book')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input language book', max_length=20, verbose_name='Language book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input name publisher', max_length=20, verbose_name='Publisher book')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input status book', max_length=20, verbose_name='Status book')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Input title book', max_length=200, verbose_name='Book title')),
                ('year', models.CharField(help_text='Input year publications', max_length=4, verbose_name='Year publications')),
                ('summary', models.TextField(help_text='Input short summary about book', max_length=1000, verbose_name='Annotation book')),
                ('isbn', models.CharField(help_text='Input 13 syvols isbn', max_length=13, verbose_name='Book isbn')),
                ('price', models.DecimalField(decimal_places=2, help_text='Input price book', max_digits=7, verbose_name='Price book')),
                ('photo', models.ImageField(help_text='Input image book', upload_to='books/%Y/%m/%d', verbose_name='Image book')),
                ('author', models.ManyToManyField(help_text='Choice author book', to='catalog.author', verbose_name='Author(authors) book')),
                ('genre', models.ForeignKey(help_text='Choice genre', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Genre book')),
                ('language', models.ForeignKey(help_text='Choice lang', on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Lang book')),
                ('publisher', models.ForeignKey(help_text='Choice publisher', on_delete=django.db.models.deletion.CASCADE, to='catalog.publisher', verbose_name='Publisher book')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Input inv number', max_length=20, null=True, verbose_name='Inv number book')),
                ('due_back', models.DateField(blank=True, help_text='Input end status', null=True, verbose_name='Date end status')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Edit status book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Status book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
